### PR TITLE
Release candidate

### PR DESCRIPTION
**Pull request by raphaelhuefner**
Hey @mbeacom ,

This time, please review the **complete PR**. I think that now it is usable as it is, but of course like any other software this **will benefit from a thorough review**.

Thank you!
Raphael

##### Description

This is a Python client for the Gitcoin API at https://gitcoin.co/api/v0.1/bounties/ .

##### Checklist

- [x] linter status: 100% pass
    - Since I am new to Python, I am running `pycodestyle`, `flake8`, `pylint` and `pydocstyle` locally. I am not sure if and how to integrate that into your project setup.
- [ ] commit message follows [commit guidelines](https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit)
    - There is 1 commit message which is 112 columns long, that was before I found https://github.com/gitcoinco/web/blob/master/docs/CONTRIBUTING.md#step-4-commit ... Do you want me to rewrite that or could that be resolved with squashing?

##### Affected core subsystem(s)

- API as defined in https://github.com/gitcoinco/web/blob/master/app/dashboard/router.py

##### Testing

There is code included which runs this API client against the live API, you can run that with `pytest --liveapi ./tests/` .

The reason I made them optional with the `--liveapi` CLI option is that occasionally, those live tests would break because of net outages or similar, and would in turn break the Travis builds.

##### Refers/Fixes

Refs: https://gitcoin.co/issue/gitcoinco/web/1185/467
Refs: https://github.com/gitcoinco/web/issues/1185

### CODE REVIEW

**Comment by owocki** [comment]
looking at this now

**Comment by owocki** [comment]
> pip install gitcoin

this doesnt seem to work.  i suppose we need to submit to pypi?

other than that, this LGTM.. @mbeacom what do you think?

**Comment by owocki** [comment]
@raphaelhuefner thank you very much.  im excited about this!

**Comment by SaptakS** [comment]
> this doesnt seem to work. i suppose we need to submit to pypi?

Yes. We will need to package it and upload to PyPI. We can first upload to Test PyPI and install and check everything works perfectly with `pip install` and then upload to PyPI

**Comment by raphaelhuefner** [comment]
@owocki @mbeacom @SaptakS Published on PyPi now, please try installing it again:

```shell
pip install gitcoin
```

Please name some PyPi username(s) you would like to have **added as owners** of https://pypi.org/project/gitcoin/ .

I think that should wrap up this bounty, right?

**Comment by raphaelhuefner** [comment]
My apologies: Sorry if the ", right?" bit in the previous comment sounds rude. I blame my ESL.

Why the long silence here:

I understood Saptak's comment so that someone on the Gitcoin.co team would publish to PyPi and that in the process the PyPi package name would belong to Gitcoin. So I felt that the ball was in your court and lost sight of this PR a bit.

After submitting another bounty I had a bit of a breather and re-read Saptak's comment and realized that it could also be understood that the ball was in my court.

As per Saptak's suggestion I published on TestPyPI first and **only then** did I realize that I was allowed to add more package owners. So I went ahead and published on the real PyPi as well, for the ease of testing this PR.

But I feel uncomfortable "cyber-squatting" the `gitcoin` PyPi package name and would prefer to transfer ownership to the Gitcoin team as soon as possible. I would feel honored to stay listed as (co-)maintainer, if you wish.

**Comment by owocki** [comment]
sorry for the radio silence on this; and thanks for the bump.    this just fell off our task list.  per our convo in slack @mbeacom is gonna accept the gitcoin pkg into the pypi repo ( we should probably also update the docs somewhere about this)

**Pull request merged**
